# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";

              docker build -t lynlab/lynlab-web:latest .;
              docker push lynlab/lynlab-web:latest;

              if [ -n "${CIRCLE_TAG}" ]; then
                docker build -t lynlab/lynlab-web:${CIRCLE_TAG} .;
                docker push lynlab/lynlab-web:${CIRCLE_TAG};
              fi
            fi
